/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as publicRegisterRouteImport } from './pages/(public)/register'
import { Route as publicLoginRouteImport } from './pages/(public)/login'
import { Route as publicForgotPasswordRouteImport } from './pages/(public)/forgot-password'
import { Route as MeHomeIndexRouteImport } from './pages/me/home/index'
import { Route as publicPasswordResetTokenRouteImport } from './pages/(public)/password/reset/$token'

const publicRegisterRoute = publicRegisterRouteImport.update({
  id: '/(public)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicForgotPasswordRoute = publicForgotPasswordRouteImport.update({
  id: '/(public)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MeHomeIndexRoute = MeHomeIndexRouteImport.update({
  id: '/me/home/',
  path: '/me/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPasswordResetTokenRoute =
  publicPasswordResetTokenRouteImport.update({
    id: '/(public)/password/reset/$token',
    path: '/password/reset/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof publicForgotPasswordRoute
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/me/home/': typeof MeHomeIndexRoute
  '/password/reset/$token': typeof publicPasswordResetTokenRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof publicForgotPasswordRoute
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/me/home': typeof MeHomeIndexRoute
  '/password/reset/$token': typeof publicPasswordResetTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/forgot-password': typeof publicForgotPasswordRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/register': typeof publicRegisterRoute
  '/me/home/': typeof MeHomeIndexRoute
  '/(public)/password/reset/$token': typeof publicPasswordResetTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/me/home/'
    | '/password/reset/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/me/home'
    | '/password/reset/$token'
  id:
    | '__root__'
    | '/(public)/forgot-password'
    | '/(public)/login'
    | '/(public)/register'
    | '/me/home/'
    | '/(public)/password/reset/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicForgotPasswordRoute: typeof publicForgotPasswordRoute
  publicLoginRoute: typeof publicLoginRoute
  publicRegisterRoute: typeof publicRegisterRoute
  MeHomeIndexRoute: typeof MeHomeIndexRoute
  publicPasswordResetTokenRoute: typeof publicPasswordResetTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/register': {
      id: '/(public)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/forgot-password': {
      id: '/(public)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof publicForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/home/': {
      id: '/me/home/'
      path: '/me/home'
      fullPath: '/me/home/'
      preLoaderRoute: typeof MeHomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/password/reset/$token': {
      id: '/(public)/password/reset/$token'
      path: '/password/reset/$token'
      fullPath: '/password/reset/$token'
      preLoaderRoute: typeof publicPasswordResetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  publicForgotPasswordRoute: publicForgotPasswordRoute,
  publicLoginRoute: publicLoginRoute,
  publicRegisterRoute: publicRegisterRoute,
  MeHomeIndexRoute: MeHomeIndexRoute,
  publicPasswordResetTokenRoute: publicPasswordResetTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
